lib /EXTRACT:./xed-encoder-hl.obj libxed.lib
lib /EXTRACT:./xed-inst-printer.obj libxed.lib
lib /EXTRACT:./xed-encode-isa-functions.obj libxed.lib
lib /EXTRACT:./xed-iform-map.obj libxed.lib
lib /EXTRACT:./xed-table-sizes.obj libxed.lib
lib /EXTRACT:./xed-operand-values-interface-repl.obj libxed.lib
lib /EXTRACT:./xed-decoded-inst.obj libxed.lib
lib /EXTRACT:./xed-version.obj libxed.lib
lib /EXTRACT:./xed-disas.obj libxed.lib
lib /EXTRACT:./xed-state.obj libxed.lib
lib /EXTRACT:./xed-enc-dec.obj libxed.lib
lib /EXTRACT:./xed-portability.obj libxed.lib
lib /EXTRACT:./xed-decode-traverse.obj libxed.lib
lib /EXTRACT:./xed-isa-set.obj libxed.lib
lib /EXTRACT:./xed-init.obj libxed.lib
lib /EXTRACT:./xed-flags.obj libxed.lib
lib /EXTRACT:./xed-operand-action.obj libxed.lib
lib /EXTRACT:./xed-reg-class.obj libxed.lib
lib /EXTRACT:./xed-inst.obj libxed.lib
lib /EXTRACT:./xed-agen.obj libxed.lib
lib /EXTRACT:./xed-immed.obj libxed.lib
lib /EXTRACT:./xed-util.obj libxed.lib
lib /EXTRACT:./xed-graph-node.obj libxed.lib
lib /EXTRACT:./xed-operand-values-interface.obj libxed.lib
lib /EXTRACT:./xed-immdis.obj libxed.lib
lib /EXTRACT:./xed-encode.obj libxed.lib
lib /EXTRACT:./xed-decode-cache.obj libxed.lib
lib /EXTRACT:./xed-decode.obj libxed.lib
lib /EXTRACT:./xed-encoder-26.obj libxed.lib
lib /EXTRACT:./xed-encoder-9.obj libxed.lib
lib /EXTRACT:./xed-exception-enum.obj libxed.lib
lib /EXTRACT:./xed-reg-role-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-13.obj libxed.lib
lib /EXTRACT:./xed-error-enum.obj libxed.lib
lib /EXTRACT:./xed-extension-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-15.obj libxed.lib
lib /EXTRACT:./xed-flag-action-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-10.obj libxed.lib
lib /EXTRACT:./xed-encoder-5.obj libxed.lib
lib /EXTRACT:./xed-encoder-17.obj libxed.lib
lib /EXTRACT:./xed-encoder-18.obj libxed.lib
lib /EXTRACT:./xed-nonterminal-enum.obj libxed.lib
lib /EXTRACT:./xed-init-operand-sequences.obj libxed.lib
lib /EXTRACT:./xed-encoder-31.obj libxed.lib
lib /EXTRACT:./xed-encoder-23.obj libxed.lib
lib /EXTRACT:./xed-operand-width-enum.obj libxed.lib
lib /EXTRACT:./xed-reg-enum.obj libxed.lib
lib /EXTRACT:./xed-init-next-nodes.obj libxed.lib
lib /EXTRACT:./xed-extractor.obj libxed.lib
lib /EXTRACT:./xed-encoder-28.obj libxed.lib
lib /EXTRACT:./xed-operand-ctype-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-25.obj libxed.lib
lib /EXTRACT:./xed-init-inst-table-1.obj libxed.lib
lib /EXTRACT:./xed-operand-action-enum.obj libxed.lib
lib /EXTRACT:./xed-init-decode-graph.obj libxed.lib
lib /EXTRACT:./xed-encoder-8.obj libxed.lib
lib /EXTRACT:./xed-attributes-init.obj libxed.lib
lib /EXTRACT:./xed-iform-max.obj libxed.lib
lib /EXTRACT:./xed-lookup-functions.obj libxed.lib
lib /EXTRACT:./xed-category-enum.obj libxed.lib
lib /EXTRACT:./xed-operand-element-type-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-30.obj libxed.lib
lib /EXTRACT:./xed-encoder-11.obj libxed.lib
lib /EXTRACT:./xed-operand-convert-enum.obj libxed.lib
lib /EXTRACT:./xed-encoder-19.obj libxed.lib
lib /EXTRACT:./xed-encoder-6.obj libxed.lib
lib /EXTRACT:./xed-init-inst-table-data.obj libxed.lib
lib /EXTRACT:./xed-encoder-20.obj libxed.lib
