// 

int __cdecl wsprintf(LPTSTR lpOut,...);
int __cdecl wsprintfA(LPTSTR lpOut,...);
int __cdecl wsprintfW(LPTSTR lpOut,...);

BOOL __stdcall DestroyWindow(HWND hWnd);
BOOL __stdcall EndDialog(HWND hDlg,int nResult);
BOOL __stdcall EndPaint(HWND hWnd,const PAINTSTRUCT *lpPaint);
BOOL __stdcall GetClientRect(HWND hWnd,LPRECT lpRect);
BOOL __stdcall GetWindowRect(HWND hWnd,RECT * lpRect);
BOOL __stdcall ShowWindow(HWND hWnd,int nCmdShow);
BOOL __stdcall TranslateMessage(const MSG *lpMsg);
BOOL __stdcall UpdateWindow(HWND hWnd);
COLORREF __stdcall SetPixel(HDC,int,int,COLORREF);
HDC __stdcall BeginPaint(HWND hWnd,PAINTSTRUCT *lpPaint);
HLOCAL __stdcall LocalFree(HLOCAL hMem);
HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName);
int __stdcall DrawTextA(HDC hDC,LPCSTR lpString,int nCount,LPRECT lpRect,UINT uFormat);
void __stdcall PostQuitMessage(int nExitCode);


// hxd
void __stdcall GetStartupInfo(LPSTARTUPINFO lpStartupInfo);
void __stdcall GetStartupInfoA(LPSTARTUPINFO lpStartupInfo);
void __stdcall GetStartupInfoW(LPSTARTUPINFO lpStartupInfo);
int __stdcall EditWndProc(DWORD hWnd,DWORD uMsg,DWORD wParam,DWORD lParam);
int __stdcall ActivateKeyboardLayout(KeyboardLayoutHandle hkl,UINT Flags);
int __stdcall AddClipboardFormatListener(HWND hwnd);
int __stdcall AdjustWindowRect(LPRECT lpRect,DWORD dwWinStyle,BOOL bMenu);
int __stdcall AdjustWindowRectEx(LPRECT lpRect,DWORD dwWinStyle,BOOL bMenu,DWORD dwEsStyle);
int __stdcall AllowActivateDetachQueuesSetFocus();
int __stdcall AllowSetForegroundWindow(DWORD dwProcessId);
int __stdcall AnimateWindow(HWND hWnd,DWORD dwTime,DWORD dwFlags);
int __stdcall AnyPopup();
int __stdcall AppendMenu(HMENU hMenu,UINT uFlags,UINT_PTR uIDNewItem,LPCTSTR lpNewItem);
int __stdcall AppendMenuA(HMENU hMenu,UINT wFlags,UINT_PTR wIDNewItem,LPCTSTR lpNewItem);
int __stdcall AppendMenuW(HMENU hMenu,UINT wFlags,UINT_PTR wIDNewItem,LPCTSTR lpNewItem);
int __stdcall ArrangeIconicWindows(HWND hwnd);
int __stdcall AttachThreadInput(DWORD idAttach,DWORD idAttachTo,BOOL fAttach);
int __stdcall BeginDeferWindowPos(int nNumWindows);
int __stdcall BeginPaint(HWND hwnd,LPPAINTSTRUCT lpPaint);
int __stdcall BlockInput(BOOL fBlockIt);
int __stdcall BringWindowToTop(HWND hWnd);
int __stdcall BroadcastSystemMessage(DWORD dwFlags,LPDWORD lpdwRecipients,UINT uiMessage,WPARAM wParam,LPARAM Param);
// int __stdcall BroadcastSystemMessageEx(DWORD dwFlags,LPDWORD lpdwRecipients,UINT uiMessage,WPARAM wParam,LPARAM lParam,PBSMINFO pBSMInfo);
int __stdcall CalculatePopupWindowPosition(const POINT* anchorPoint,const SIZE* windowSize,UINT flags,RECT* excludeRect,RECT* popupWindowPosition);
int __stdcall CallMsgFilter(LPMSG lpMsg,int nCode);
int __stdcall CallNextHookEx(HHOOK hhk,int nCode,WPARAM wParam,LPARAM lParam);
int __stdcall CallWindowProc(WNDPROC lpPrevWndFunc,HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall CallWindowProcA(WNDPROC lpPrevWndFunc,HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall CallWindowProcW(WNDPROC lpPrevWndFunc,HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall CascadeWindows(HWND hwndParent,UINT wHow,const RECT* lpRect,UINT cKids,const HWND* lpKids);
int __stdcall ChangeClipboardChain(HWND hWndRemove,HWND hWndNewNext);
int __stdcall ChangeDisplaySettings(DEVMODE* lpDevMode,DWORD dwflags);
int __stdcall ChangeDisplaySettingsEx(LPCTSTR lpszDeviceName,DEVMODE* lpDevMode,HWND hwnd,DWORD dwflags,LPVOID lParam);
int __stdcall ChangeWindowMessageFilter(UINT message,DWORD dwFlag);
//int __stdcall ChangeWindowMessageFilterEx(HWND hWnd,UINT message,DWORD action,PCHANGEFILTERSTRUCT pChangeFilterStruct);
int __stdcall CharLower(LPTSTR lpsz);
int __stdcall CharLowerA(LPTSTR lpsz);
int __stdcall CharLowerBuff(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharLowerBuffA(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharLowerBuffW(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharLowerW(LPTSTR lpsz);
int __stdcall CharNext(LPCTSTR lpsz);
int __stdcall CharNextA(LPCTSTR lpsz);
int __stdcall CharNextExA(WORD CodePage,LPCSTR lpCurrentChar,DWORD dwFlags);
int __stdcall CharNextW(LPCTSTR lpsz);
int __stdcall CharPrev(LPCTSTR lpszStart,LPCTSTR lpszCurrent);
int __stdcall CharPrevA(LPCTSTR lpszStart,LPCTSTR lpszCurrent);
int __stdcall CharPrevExA(WORD CodePage,LPCSTR lpStart,LPCSTR lpCurrentChar,DWORD dwFlags);
int __stdcall CharToOem(LPCTSTR lpszSrc,LPSTR lpszDst);
int __stdcall CharToOemA(LPCTSTR lpszSrc,LPSTR lpszDst);
int __stdcall CharToOemBuff(LPCTSTR lpszSrc,LPSTR lpszDst,DWORD cchDstLength);
int __stdcall CharToOemW(LPCTSTR lpszSrc,LPSTR lpszDst);
int __stdcall CharUpper(LPTSTR lpsz);
int __stdcall CharUpperA(LPTSTR lpsz);
int __stdcall CharUpperBuff(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharUpperBuffA(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharUpperBuffW(LPTSTR lpsz,DWORD cchLength);
int __stdcall CharUpperW(LPTSTR lpsz);
int __stdcall CheckDlgButton(HWND hDlg,int nIDButton,UINT uCheck);
int __stdcall CheckMenuItem(HMENU hmenu,UINT uIDCheckItem,UINT uCheck);
int __stdcall CheckMenuRadioItem(HMENU hmenu,UINT idFirst,UINT idLast,UINT idCheck,DWORD uFlags);
int __stdcall CheckRadioButton(HWND hDlg,int nIDFirstButton,int nIDLastButton,int nIDCheckButton);
int __stdcall ChildWindowFromPoint(HWND hWndParent,POINT Point);
int __stdcall ChildWindowFromPointEx(HWND hwndParent,POINT pt,UINT uFlags);
int __stdcall ClientToScreen(HWND hWnd,LPPOINT lpPoint);
int __stdcall ClipCursor(const RECT* lpRect);
int __stdcall CloseClipboard();
int __stdcall CloseDesktop(HDESK hDesktop);
int __stdcall CloseGestureInfoHandle(HGESTUREINFO hGestureInfo);
int __stdcall CloseTouchInputHandle(HTOUCHINPUT hTouchInput);
int __stdcall CloseWindow(HWND hWnd);
int __stdcall CloseWindowStation(HWINSTA hWinSta);
int __stdcall CopyAcceleratorTable(HACCEL hAccelSrc,LPACCEL lpAccelDst,int cAccelEntries);
int __stdcall CopyAcceleratorTableA(HACCEL hAccelSrc,LPACCEL IpAcceIDst,int cAccelEntries);
int __stdcall CopyAcceleratorTableW(HACCEL hAccelSrc,LPACCEL IpAcceIDst,int cAccelEntries);
int __stdcall CopyCursor(HCURSOR pcur);
int __stdcall CopyIcon(HICON hIcon);
int __stdcall CopyImage(HANDLE hImage,UINT uType,int cxDesired,int cyDesired,UINT fuFlags);
int __stdcall CopyRect(LPRECT lprcDst,const RECT* lprcSrc);
int __stdcall CountClipboardFormats();
int __stdcall CreateAcceleratorTable(LPACCEL lpaccl,int cEntries);
int __stdcall CreateAcceleratorTableW(LPACCEL lpaccl,int cEntries);
int __stdcall CreateCaret(HWND hWnd,HBITMAP hBitmap,int nWidth,int nHeight);
int __stdcall CreateCursor(HINSTANCE hInst,int xHotSpot,int yHotSpot,int nWidth,int nHeight,const VOID* pvANDPlane,const VOID* pvXORPlane);
int __stdcall CreateDesktop(LPCTSTR lpszDesktop,LPCTSTR lpszDevice,LPDEVMODE pDevmode,DWORD dwFlags,DWORD dwDesiredAccess,LPSECURITY_ATTRIBUTES lpsa);
int __stdcall CreateDesktopEx(LPCTSTR lpszDesktop,LPCTSTR lpszDevice,LPDEVMODE pDevmode,DWORD dwFlags,DWORD dwDesiredAccess,LPSECURITY_ATTRIBUTES lpsa,ULONG ulHeapSize,PVOID pvoid);
int __stdcall CreateDialogIndirectParam(HINSTANCE hInstance,LPCDLGTEMPLATE lpTemplate,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM lParamInit);
int __stdcall CreateDialogIndirectParamA(HINSTANCE hInstance,LPCDLGTEMPLATE lpTemplate,HWND hWndParent,DLGPROC lpDialogFun,LPARAM lParamInit);
int __stdcall CreateDialogIndirectParamW(HINSTANCE hInstance,LPCDLGTEMPLATE lpTemplate,HWND hWndParent,DLGPROC lpDialogFun,LPARAM lParamInit);
int __stdcall CreateDialogParam(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM lParamInit);
int __stdcall CreateDialogParamA(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM dwInitParam);
int __stdcall CreateDialogParamW(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM dwInitParam);
int __stdcall CreateIcon(HINSTANCE hInstance,int nWidth,int Height,BYTE cPlanes,BYTE cBitsPixel,const BYTE* lpbANDbits,const BYTE* lpbXORbits);
int __stdcall CreateIconFromResource(PBYTE presbits,DWORD dwResSize,BOOL fIcon,DWORD dwVersion);
int __stdcall CreateIconFromResourceEx(PBYTE pbIconBits,DWORD cbIconBits,BOOL fIcon,DWORD dwVersion,int cxDesired,int cyDesired,UINT uFlags);
int __stdcall CreateIconIndirect(PICONINFO piconinfo);
int __stdcall CreateMDIWindow(LPCTSTR lpClassName,LPCTSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent,HINSTANCE hInstance,LPARAM lParam);
int __stdcall CreateMDIWindowA(LPCTSTR lpClassName,LPCTSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent,HINSTANCE hInstance,LPARAM lParam);
int __stdcall CreateMDIWindowW(LPCTSTR lpClassName,LPCTSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent,HINSTANCE hInstance,LPARAM lParam);
int __stdcall CreateMenu();
int __stdcall CreatePopupMenu();
int __stdcall CreateWindow(LPCTSTR lpClassName,LPCTSTR lpWindowName,DWORD dwStyle,int x,int y,int nWidth,int nHeight,HWND hWndParent,HMENU hMenu,HINSTANCE hInstance,LPVOID lpParam);
HWND __stdcall CreateWindowEx(DWORD dwExStyle,LPCSTR lpClassName,LPCSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent,HMENU hMenu,HINSTANCE hInstance,LPVOID lpParam);
HWND __stdcall CreateWindowExA(DWORD dwExStyle,LPCSTR lpClassName,LPCSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent,HMENU hMenu,HINSTANCE hInstance,LPVOID lpParam);
HWND __stdcall CreateWindowExW(DWORD dwExStyle,LPCWSTR lpClassName,LPCWSTR lpWindowName,DWORD dwStyle,int X,int Y,int nWidth,int nHeight,HWND hWndParent ,HMENU hMenu,HINSTANCE hInstance,LPVOID lpParam);
int __stdcall CreateWindowStation(LPCTSTR lpwinsta,DWORD dwFlags,DWORD dwDesiredAccess,LPSECURITY_ATTRIBUTES lpsa);
int __stdcall DdeAbandonTransaction(DWORD idInst,HCONV hConv,DWORD idTransaction);
int __stdcall DdeAccessData(HDDEDATA hData,LPDWORD pcbDataSize);
int __stdcall DdeAddData(HDDEDATA hData,LPBYTE pSrc,DWORD cb,DWORD cbOff);
int __stdcall DdeClientTransaction(LPBYTE pData,DWORD cbData,HCONV hConv,HSZ hszItem,UINT wFmt,UINT wType,DWORD dwTimeout,LPDWORD pdwResult);
int __stdcall DdeCmpStringHandles(HSZ hsz1,HSZ hsz2);
int __stdcall DdeConnect(DWORD idInst,HSZ hszService,HSZ hszTopic,PCONVCONTEXT pCC);
int __stdcall DdeConnectList(DWORD idInst,HSZ hszService,HSZ hszTopic,HCONVLIST hConvList,PCONVCONTEXT pCC);
int __stdcall DdeCreateDataHandle(DWORD idInst,LPBYTE pSrc,DWORD cb,DWORD cbOff,HSZ hszItem,UINT wFmt,UINT afCmd);
int __stdcall DdeCreateStringHandle(DWORD idInst,LPTSTR psz,int iCodePage);
int __stdcall DdeDisconnect(HCONV hConv);
int __stdcall DdeDisconnectList(HCONVLIST hConvList);
int __stdcall DdeEnableCallback(DWORD idInst,HCONV hConv,UINT wCmd);
int __stdcall DdeFreeDataHandle(HDDEDATA hData);
int __stdcall DdeFreeStringHandle(DWORD idInst,HSZ hsz);
int __stdcall DdeGetData(HDDEDATA hData,LPBYTE pDst,DWORD cbMax,DWORD cbOff);
int __stdcall DdeGetLastError(DWORD idInst);
int __stdcall DdeImpersonateClient(HCONV hConv);
//int __stdcall DdeInitialize(LPDWORD pidInst,PFNCALLBACK pfnCallback,DWORD afCmd,DWORD ulRes);
int __stdcall DdeKeepStringHandle(DWORD idInst,HSZ hsz);
int __stdcall DdeNameService(DWORD idInst,UINT hsz1,UINT hsz2,UINT afCmd);
int __stdcall DdePostAdvise(DWORD idInst,HSZ hszTopic,HSZ hszItem);
int __stdcall DdeQueryConvInfo(HCONV hConv,DWORD idTransaction,PCONVINFO pConvInfo);
int __stdcall DdeQueryNextServer(HCONVLIST hConvList,HCONV hConvPrev);
int __stdcall DdeQueryString(DWORD idInst,HSZ hsz,LPTSTR psz,DWORD cchMax,int iCodePage);
int __stdcall DdeReconnect(HCONV hConv);
int __stdcall DdeSetQualityOfService(HWND hwndClient,const SECURITY_QUALITY_OF_SERVICE* pqosNew,PSECURITY_QUALITY_OF_SERVICE pqosPrev);
int __stdcall DdeSetUserHandle(HCONV hConv,DWORD id,DWORD_PTR hUser);
int __stdcall DdeUnaccessData(HDDEDATA hData);
int __stdcall DdeUninitialize(DWORD idInst);
int __stdcall DefDlgProc(HWND hDlg,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall DefDlgProcW(HWND hDlg,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall DefFrameProc(HWND hWnd,HWND hWndMDIClient,UINT uMsg,WPARAM wParam,LPARAM lParam);
int __stdcall DefFrameProcA(HWND hWnd,HWND hWndMDIClient,UINT uMsg,WPARAM wParam,LPARAM lParam);
int __stdcall DefFrameProcW(HWND hWnd,HWND hWndMDIClient,UINT uMsg,WPARAM wParam,LPARAM lParam);
int __stdcall DefMDIChildProc(HWND hWnd,UINT uMsg,WPARAM wParam,LPARAM lParam);
int __stdcall DefMDIChildProcA(HWND hWnd,UINT uMsg,WPARAM wParam,LPARAM lParam);
int __stdcall DefRawInputProc(PRAWINPUT* paRawInput,INT nInput,UINT cbSizeHeader);
LRESULT __stdcall DefWindowProc(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
LRESULT __stdcall DefWindowProcA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
LRESULT __stdcall DefWindowProcW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall DeferWindowPos(HDWP hWinPosInfo,HWND hWnd,HWND hWndInsertAfter,int x,int y,int cx,int cy,UINT uFlags);
int __stdcall DeleteMenu(HMENU hMenu,UINT uPosition,UINT uFlags);
int __stdcall DeregisterShellHookWindow(HWND hWnd);
int __stdcall DestroyAcceleratorTable(HACCEL hAccel);
int __stdcall DestroyCaret();
int __stdcall DestroyCursor(HCURSOR hCursor);
int __stdcall DestroyIcon(HICON hIcon);
int __stdcall DestroyMenu(HMENU hMenu);
int __stdcall DestroyWindow(HWND hWnd);
int __stdcall DialogBoxIndirectParam(HINSTANCE hInstance,LPCDLGTEMPLATE hDialogTemplate,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM dwInitParam);
int __stdcall DialogBoxIndirectParamA(HINSTANCE hInstance,LPCDLGTEMPLATE hDialogTemplate,HWND hWndParent,DLGPROC pDialogFunc,LPARAM dwInitParam);
int __stdcall DialogBoxIndirectParamW(HINSTANCE hInstance,LPCDLGTEMPLATE hDialogTemplate,HWND hWndParent,DLGPROC pDialogFunc,LPARAM dwInitParam);
int __stdcall DialogBoxParam(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWndParent,DLGPROC lpDialogFunc,LPARAM dwInitParam);
int __stdcall DialogBoxParamA(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWnd,DLGPROC lpDialogFunc,LPARAM dwInitParam);
int __stdcall DialogBoxParamW(HINSTANCE hInstance,LPCTSTR lpTemplateName,HWND hWnd,DLGPROC lpDialogFunc,LPARAM dwInitParam);
long __stdcall DispatchMessage(const MSG *lpMsg);
long __stdcall DispatchMessageA(const MSG *lpMsg);
long __stdcall DispatchMessageW(const MSG *lpMsg);
int __stdcall DlgDirList(HWND hDlg,LPTSTR lpPathSpec,int nIDListBox,int nIDStaticPath,UINT uFileType);
int __stdcall DlgDirListComboBox(HWND hDlg,LPTSTR lpPathSpec,int nIDComboBox,int nIDStaticPath,UINT uFiletype);
int __stdcall DlgDirSelectComboBoxEx(HWND hDlg,LPTSTR lpString,int nCount,int nIDComboBox);
int __stdcall DlgDirSelectEx(HWND hDlg,LPTSTR lpString,int nCount,int nIDListBox);
int __stdcall DragDetect(HWND hwnd,POINT pt);
int __stdcall DrawAnimatedRects(HWND hWnd,int dAni,const RECT* lprcFrom,const RECT* lprcTo);
int __stdcall DrawCaption(HWND hwnd,HDC hdc,LPCRECT lprc,UINT uFlags);
int __stdcall DrawEdge(HDC hDC,LPRECT qrc,UINT edge,UINT grfFlags);
int __stdcall DrawFocusRect(HDC hDC,const RECT* lprc);
int __stdcall DrawFrameControl(HDC hDC,LPRECT lprc,UINT uType,UINT uState);
int __stdcall DrawIcon(HDC hDC,int X,int Y,HICON hIcon);
int __stdcall DrawIconEx(HDC hDC,int xLeft,int yTop,HICON hIcon,int cxWidth,int cyWidth,UINT istepIfAniCur,HBRUSH hbrFlickerFreeDraw,UINT diFlags);
int __stdcall DrawMenuBar(HWND hWnd);
int __stdcall DrawState(HDC hdc,HBRUSH hbr,DRAWSTATEPROC lpOutputFunc,LPARAM lData,WPARAM wData,int x,int y,int cx,int cy,UINT fuFlags);
int __stdcall DrawStateA(HDC hDC,HBRUSH hbr,DRAWSTATEPROC lpOutputFunc,LPARAM lData,WPARAM wData,int X,int Y,int cx,int cy,UINT fuFlags);
int __stdcall DrawStateW(HDC hDC,HBRUSH hbr,DRAWSTATEPROC lpOutputFunc,LPARAM lData,WPARAM wData,int X,int Y,int cx,int cy,UINT fuFlags);
int __stdcall DrawText(HDC hDC,LPCTSTR lpchText,int nCount,LPRECT lpRect,UINT uFormat);
int __stdcall DrawTextA(HDC hDC,LPCTSTR lpString,int nCount,LPRECT lpRect,UINT uFormat);
int __stdcall DrawTextEx(HDC hdc,LPTSTR lpchText,int cchText,LPRECT lprc,UINT dwDTFormat,LPDRAWTEXTPARAMS lpDTParams);
int __stdcall DrawTextExA(HDC hDC,LPTSTR lpchText,int cchText,LPRECT lprc,UINT dwDTFormat,LPDRAWTEXTPARAMS lpDTParams);
int __stdcall DrawTextExW(HDC hDC,LPTSTR lpchText,int cchText,LPRECT lprc,UINT dwDTFormat,LPDRAWTEXTPARAMS lpDTParams);
int __stdcall DrawTextW(HDC hDC,LPCTSTR lpString,int nCount,LPRECT lpRect,UINT uFormat);
int __stdcall EmptyClipboard();
int __stdcall EnableMenuItem(HMENU hMenu,UINT uIDEnableItem,UINT uEnable);
int __stdcall EnableScrollBar(HWND hWnd,UINT WSBflags,UINT wArrows);
int __stdcall EnableWindow(HWND hWnd,BOOL bEnable);
int __stdcall EndDeferWindowPos(HDWP hWinPosInfo);
int __stdcall EndDialog(HWND hDlg,INT_PTR nResult);
int __stdcall EndMenu();
int __stdcall EndPaint(HWND hWnd,const PAINTSTRUCT* lpPaint);
int __stdcall EndTask(HWND hWnd,BOOL fShutDown,BOOL fForce);
int __stdcall EnumChildWindows(HWND hWndParent,WNDENUMPROC lpEnumFunc,LPARAM lParam);
int __stdcall EnumClipboardFormats(UINT format);
int __stdcall EnumDesktopWindows(HDESK hDesktop,WNDENUMPROC lpfn,LPARAM lParam);
int __stdcall EnumDesktops(HWINSTA hwinsta,DESKTOPENUMPROC lpEnumFunc,LPARAM lParam);
int __stdcall EnumDisplayDevices(LPCTSTR lpReserved,DWORD iDeviceNum,PDISPLAY_DEVICE pDisplayDevice,DWORD dwFlags);
int __stdcall EnumDisplayMonitors(DWORD hDesktop,DWORD lpfn,DWORD lParam);
int __stdcall EnumDisplayMonitors(HDC hdc,LPCRECT lprcClip,MONITORENUMPROC lpfnEnum,LPARAM dwData);
int __stdcall EnumDisplaySettings(LPCTSTR lpszDeviceName,int iModeNum,DEVMODE* lpDevMode);
int __stdcall EnumDisplaySettingsA(LPCTSTR lpszDeviceName,int iModeNum,DEVMODE* lpDevMode);
int __stdcall EnumDisplaySettingsEx(LPCTSTR lpszDeviceName,DWORD iModeNum,DEVMODE* lpDevMode,DWORD dwFlags);
int __stdcall EnumProps(HWND hWnd,PROPENUMPROC lpEnumFunc);
int __stdcall EnumPropsEx(HWND hWnd,PROPENUMPROCEX lpEnumFunc,LPARAM lParam);
int __stdcall EnumThreadWindows(DWORD dwThreadId,WNDENUMPROC lpfn,LPARAM lParam);
int __stdcall EnumWindowStations(WINSTAENUMPROC lpEnumFunc,LPARAM lParam);
int __stdcall EnumWindows(WNDENUMPROC lpEnumFunc,LPARAM lParam);
int __stdcall EqualRect(const RECT* lprc1,const RECT* lprc2);
int __stdcall ExcludeUpdateRgn(HDC hDC,HWND hWnd);
int __stdcall ExitWindowsEx(UINT uFlags,DWORD dwReserved);
int __stdcall FillRect(HDC hDC,const RECT* lprc,HBRUSH hbr);
int __stdcall FindWindow(LPCTSTR lpClassName,LPCTSTR lpWindowName);
int __stdcall FindWindowA(LPCTSTR lpClassName,LPCTSTR lpWindowName);
int __stdcall FindWindowEx(HWND hwndParent,HWND hwndChildAfter,LPCTSTR lpszClass,LPCTSTR lpszWindow);
int __stdcall FindWindowExA(HWND hwndParent,HWND hwndChildAfter,LPCTSTR lpszClass,LPCTSTR pszWindow);
int __stdcall FindWindowExW(HWND hwndParent,HWND hwndChildAfter,LPCTSTR lpszClass,LPCTSTR pszWindow);
int __stdcall FindWindowW(LPCTSTR lpClassName,LPCTSTR lpWindowName);
int __stdcall FlashWindow(HWND hWnd,BOOL bInvert);
int __stdcall FlashWindowEx(PFLASHWINFO pfwi);
int __stdcall FrameRect(HDC hDC,const RECT* lprc,HBRUSH hbr);
int __stdcall FreeDDElParam(UINT msg,LPARAM lParam);
int __stdcall GetActiveWindow();
int __stdcall GetAltTabInfo(HWND hwnd,int iItem,PALTTABINFO pati,LPTSTR pszItemText,UINT cchItemText);
int __stdcall GetAncestor(HWND hwnd,DWORD gaFlags);
int __stdcall GetAsyncKeyState(int vKey);
int __stdcall GetCapture();
int __stdcall GetCaretBlinkTime();
int __stdcall GetCaretPos(LPPOINT lpPoint);
int __stdcall GetClassInfo(HINSTANCE hInstance,LPCTSTR lpClassName,LPWNDCLASS lpWndClass);
int __stdcall GetClassInfoA(HINSTANCE hInstance,LPCTSTR lpClassName,LPWNDCLASS lpWndClass);
int __stdcall GetClassInfoEx(HINSTANCE hinst,LPCTSTR lpszClass,LPWNDCLASSEX lpwcx);
int __stdcall GetClassInfoExA(HINSTANCE hinst,LPCTSTR lpszClass,LPWNDCLASSEX lpwcx);
int __stdcall GetClassInfoExW(HINSTANCE hinst,LPCTSTR lpszClass,LPWNDCLASSEX lpwcx);
int __stdcall GetClassInfoW(HINSTANCE hInstance,LPCTSTR lpClassName,LPWNDCLASS lpWndClass);
int __stdcall GetClassLong(HWND hWnd,int nIndex);
int __stdcall GetClassLongA(HWND hWnd,int nIndex);
int __stdcall GetClassLongW(HWND hWnd,int nIndex);
int __stdcall GetClassName(HWND hWnd,LPTSTR lpClassName,int nMaxCount);
int __stdcall GetClassNameA(HWND hWnd,LPTSTR lpBuffer,int nBufferSize);
int __stdcall GetClassNameW(HWND hWnd,LPTSTR lpBuffer,int nBufferSize);
int __stdcall GetClassWord(HWND hWnd,int nIndex);
int __stdcall GetClientRect(HWND hWnd,LPRECT lpRect);
int __stdcall GetClipCursor(LPRECT lpRect);
int __stdcall GetClipboardData(UINT uFormat);
int __stdcall GetClipboardFormatName(UINT format,LPTSTR lpszFormatName,int cchMaxCount);
int __stdcall GetClipboardFormatNameA(UINT format,LPTSTR lpBuffer,int cchMaxCount);
int __stdcall GetClipboardOwner();
int __stdcall GetClipboardSequenceNumber();
int __stdcall GetClipboardViewer();
int __stdcall GetComboBoxInfo(HWND hWndCombo,PCOMBOBOXINFO pcbi);
int __stdcall GetCursor();
int __stdcall GetCursorInfo(PCURSORINFO pci);
int __stdcall GetCursorPos(LPPOINT lpPoint);
int __stdcall GetDC(HWND hwnd);
int __stdcall GetDCEx(HWND hWnd,HRGN hrgnClip,UINT flags);
HWND __stdcall GetDesktopWindow();
int __stdcall GetDialogBaseUnits();
int __stdcall GetDlgCtrlID(HWND hwndCtl);
int __stdcall GetDlgItem(HWND hDlg,int nIDDlgItem);
int __stdcall GetDlgItemInt(HWND hDlg,int nIDDlgItem,BOOL* lpTranslated,BOOL bSigned);
int __stdcall GetDlgItemText(HWND hDlg,int nIDDlgItem,LPTSTR lpString,int nMaxCount);
int __stdcall GetDlgItemTextA(HWND hDlg,int nIDDlgItem,LPTSTR lpBuffer,int nBufferSize);
int __stdcall GetDlgItemTextW(HWND hDlg,int nIDDlgItem,LPTSTR lpBuffer,int nBufferSize);
int __stdcall GetDoubleClickTime();
int __stdcall GetFocus();
int __stdcall GetForegroundWindow();
int __stdcall GetGUIThreadInfo(DWORD idThread,LPGUITHREADINFO lpgui);
int __stdcall GetGestureConfig(HWND hwnd,DWORD dwReserved,DWORD dwFlags,PUINT pcIDs,PGESTURECONFIG pGestureConfig,UINT cbSize);
int __stdcall GetGestureExtraArgs(HGESTUREINFO hGestureInfo,UINT cbExtraArgs,PBYTE pExtraArgs);
int __stdcall GetGestureInfo(HGESTUREINFO hGestureInfo,PGESTUREINFO pGestureInfo);
int __stdcall GetGuiResources(HANDLE hProcess,DWORD uiFlags);
int __stdcall GetIconInfo(HICON hIcon,PICONINFO piconinfo);
int __stdcall GetIconInfoEx(HICON hIcon,PICONINFOEX piconinfoex);
int __stdcall GetInputState();
int __stdcall GetKBCodePage();
int __stdcall GetKeyNameText(LONG lParam,LPTSTR lpString,int nSize);
int __stdcall GetKeyNameTextA(LONG lParam,LPTSTR lpString,int nSize);
int __stdcall GetKeyNameTextW(LONG lParam,LPTSTR lpString,int nSize);
int __stdcall GetKeyState(int nVirtKey);
int __stdcall GetKeyboardLayout(DWORD dwLayout);
int __stdcall GetKeyboardLayoutList(int nBuff,HKL* lpList);
int __stdcall GetKeyboardLayoutName(LPTSTR pwszKLID);
int __stdcall GetKeyboardLayoutNameA(LPTSTR pwszKLID);
int __stdcall GetKeyboardLayoutNameW(LPTSTR pwszKLID);
int __stdcall GetKeyboardState(PBYTE lpKeyState);
int __stdcall GetKeyboardType(int nTypeFlag);
int __stdcall GetLastActivePopup(HWND hWnd);
int __stdcall GetLastInputInfo(PLASTINPUTINFO plii);
int __stdcall GetLayeredWindowAttributes(HWND hwnd,COLORREF* pcrKey,BYTE* pbAlpha,DWORD pdwFlags);
int __stdcall GetListBoxInfo(HWND hwnd);
int __stdcall GetMenu(HWND hWnd);
int __stdcall GetMenuBarInfo(HWND hwnd,UINT idObject,LONG idItem,PMENUBARINFO pmbi);
int __stdcall GetMenuCheckMarkDimensions();
int __stdcall GetMenuContextHelpId(HMENU hmenu);
int __stdcall GetMenuDefaultItem(HMENU hMenu,UINT fByPos,UINT gmdiFlags);
int __stdcall GetMenuInfo(HMENU hMenu,LPCMENUINFO lpcMenuInfo);
int __stdcall GetMenuItemCount(HMENU hMenu);
int __stdcall GetMenuItemID(HMENU hMenu,int nPos);
int __stdcall GetMenuItemInfo(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall GetMenuItemInfoA(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall GetMenuItemInfoW(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall GetMenuItemRect(HWND hWnd,HMENU hMenu,UINT uItem,LPRECT lprcItem);
int __stdcall GetMenuState(HMENU hMenu,UINT uId,UINT uFlags);
int __stdcall GetMenuString(HMENU hMenu,UINT uIDItem,LPTSTR lpString,int nMaxCount,UINT uFlag);
int __stdcall GetMenuStringA(HMENU hMenu,UINT uIDItem,LPTSTR lpBuffer,int nBufferSize,UINT uFlag);
int __stdcall GetMenuStringW(HMENU hMenu,UINT uIDItem,LPTSTR lpBuffer,int nBufferSize,UINT uFlag);
bool __stdcall GetMessage(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax);
BOOL __stdcall GetMessageA(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax);
int __stdcall GetMessageExtraInfo();
int __stdcall GetMessagePos();
int __stdcall GetMessageTime();
BOOL __stdcall GetMessageW(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax);
int __stdcall GetMonitorInfo(HMONITOR hMonitor,LPMONITORINFO lpmi);
int __stdcall GetMonitorInfoW(HMONITOR hMonitor,LPMONITORINFO lpMonitorIfno);
int __stdcall GetMouseMovePointsEx(UINT cbSize,LPMOUSEMOVEPOINT lppt,LPMOUSEMOVEPOINT lpptBuf,int nBufPoints,DWORD resolution);
int __stdcall GetNextDlgGroupItem(HWND hDlg,HWND hCtl,BOOL bPrevious);
int __stdcall GetNextDlgTabItem(HWND hDlg,HWND hCtl,BOOL bPrevious);
int __stdcall GetOpenClipboardWindow();
int __stdcall GetParent(HWND hWnd);
int __stdcall GetPhysicalCursorPos(LPPOINT lpPoint);
int __stdcall GetPriorityClipboardFormat(UINT* paFormatPriorityList,int cFormats);
int __stdcall GetProcessDefaultLayout(DWORD* pdwDefaultLayout);
int __stdcall GetProcessWindowStation();
int __stdcall GetProp(HWND hWnd,LPCTSTR lpString);
int __stdcall GetPropA(HWND hWnd,LPCTSTR lpString);
int __stdcall GetPropW(HWND hWnd,LPCTSTR lpString);
int __stdcall GetQueueStatus(DWORD flags);
int __stdcall GetRawInputBuffer(PRAWINPUT pData,PUINT pcbSize,UINT cbSizeHeader);
int __stdcall GetRawInputData(HRAWINPUT hRawInput,UINT uiCommand,LPVOID pData,PUINT pcbSize,UINT cbSizeHeader);
int __stdcall GetRawInputDeviceInfo(HANDLE hDevice,UINT uiCommand,LPVOID pData,PUINT pcbSize);
int __stdcall GetRawInputDeviceList(PRAWINPUTDEVICELIST pRawInputDeviceList,PUINT puiNumDevices,UINT cbSize);
int __stdcall GetRegisteredRawInputDevices(PRAWINPUTDEVICE pRawInputDevices,PUINT puiNumDevices,UINT cbSize);
int __stdcall GetScrollBarInfo(HWND hWnd,UINT fnBar,PSCROLLBARINFO lpsi);
int __stdcall GetScrollInfo(HWND hWnd,int fnBar,LPSCROLLINFO lpScorllInfo);
int __stdcall GetScrollPos(HWND hWnd,int nBar);
int __stdcall GetScrollRange(HWND hWnd,int nBar,LPINT lpMinPos,LPINT lpMaxPos);
int __stdcall GetShellWindow();
int __stdcall GetSubMenu(HMENU hMenu,int nPos);
int __stdcall GetSysColor(int nIndex);
int __stdcall GetSysColorBrush(int nIndex);
int __stdcall GetSystemMenu(HWND hWnd,BOOL bRevert);
int __stdcall GetSystemMetrics(int nIndex);
int __stdcall GetTabbedTextExtent(HDC hDC,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions);
int __stdcall GetTabbedTextExtentA(HDC hDC,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions);
int __stdcall GetTabbedTextExtentW(HDC hDC,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions);
int __stdcall GetThreadDesktop(DWORD dwThreadId);
int __stdcall GetTitleBarInfo(HWND hwnd,PTITLEBARINFO pti);
int __stdcall GetTopWindow(HWND hWnd);
int __stdcall GetTouchInputInfo(HTOUCHINPUT hTouchInput,UINT cInputs,PTOUCHINPUT pInputs,int cbSize);
int __stdcall GetUpdateRect(HWND hWnd,LPRECT lpRect,BOOL bErase);
int __stdcall GetUpdateRgn(HWND hWnd,HRGN hRgn,BOOL bErase);
int __stdcall GetUpdatedClipboardFormats(PUINT lpuiFormats,UINT cFormats,PUINT pcFormatsOut);
int __stdcall GetUserObjectInformation(HANDLE hObj,UINT nIndex,PVOID pvInfo,DWORD nLength,LPDWORD lpnLengthNeeded);
int __stdcall GetUserObjectInformationA(HANDLE hActiveDesktop,UINT nIndex,PVOID pvInfo,DWORD nBuffLen,LPDWORD dwSize);
int __stdcall GetUserObjectSecurity(HANDLE hObj,PSECURITY_INFORMATION pSIRequested,PSECURITY_DESCRIPTOR pSD,DWORD nLength,LPDWORD lpnLengthNeeded);
int __stdcall GetWindow(HWND hWnd,UINT uCmd);
int __stdcall GetWindowContextHelpId(HWND hWnd);
int __stdcall GetWindowDC(HWND hWnd);
int __stdcall GetWindowDisplayAffinity(HWND hWnd,DWORD* dwAffinity);
int __stdcall GetWindowInfo(HWND hwnd,PWINDOWINFO pwi);
int __stdcall GetWindowLong(HWND hWnd,int nIndex);
int __stdcall GetWindowLongA(HWND hWnd,int nIndex);
int __stdcall GetWindowLongW(HWND hWnd,int nIndex);
int __stdcall GetWindowModuleFileName(HWND hwnd,LPTSTR lpszFileName,UINT cchFileNameMax);
int __stdcall GetWindowPlacement(HWND hWnd,WINDOWPLACEMENT* lpwndpl);
int __stdcall GetWindowRect(HWND hWnd,LPRECT lpRect);
int __stdcall GetWindowRgn(HWND hWnd,HRGN hRgn);
int __stdcall GetWindowRgnBox(HWND hWnd,LPRECT lprc);
int __stdcall GetWindowText(HWND hWnd,LPTSTR lpString,int nMaxCount);
int __stdcall GetWindowTextA(HWND hWnd,LPTSTR lpString,int nMaxCount);
int __stdcall GetWindowTextLength(HWND hWnd);
int __stdcall GetWindowTextLengthA(HWND hWnd);
int __stdcall GetWindowTextLengthW(HWND hWnd);
int __stdcall GetWindowTextW(HWND hWnd,LPTSTR lpString,int nMaxCount);
int __stdcall GetWindowThreadProcessId(HWND hWnd,LPDWORD lpdwProcessId);
int __stdcall GrayString(HDC hDC,HBRUSH hBrush,GRAYSTRINGPROC lpOutputFunc,LPARAM lpData,int nCount,int X,int Y,int nWidth,int nHeight);
int __stdcall GrayStringA(HDC hDC,HBRUSH hBrush,GRAYSTRINGPROC lpOutputFunc,LPARAM lpData,int nCount,int X,int Y,int nWidth,int nHeight);
int __stdcall GrayStringW(HDC hDC,HBRUSH hBrush,GRAYSTRINGPROC lpOutputFunc,LPARAM lpData,int nCount,int X,int Y,int nWidth,int nHeight);
int __stdcall HideCaret(HWND hWnd);
int __stdcall HiliteMenuItem(HWND hwnd,HMENU hmenu,UINT uItemHilite,UINT uHilite);
int __stdcall ImpersonateDdeClientWindow(HWND hWndClient,HWND hWndServer);
int __stdcall InSendMessage();
int __stdcall InSendMessageEx(LPVOID lpReserved);
int __stdcall InflateRect(LPRECT lpRect,int x,int y);
int __stdcall InsertMenu(HMENU hMenu,UINT uPosition,UINT uFlags,UINT_PTR uIDNewItem,LPCTSTR lpNewItem);
int __stdcall InsertMenuA(HMENU hMenu,UINT nPosition,UINT wFlags,UINT_PTR wIDNewItem,LPCTSTR lpNewItem);
int __stdcall InsertMenuItem(HMENU hMenu,UINT uItem,BOOL fByPosition,LPCMENUITEMINFO lpmii);
int __stdcall InsertMenuItemA(HMENU hMenu,UINT uItem,BOOL fByPosition,LPCMENUITEMINFO lpmii);
int __stdcall InsertMenuItemW(HMENU hMenu,UINT uItem,BOOL fByPosition,LPCMENUITEMINFO lpmii);
int __stdcall InsertMenuW(HMENU hMenu,UINT nPosition,UINT wFlags,UINT_PTR wIDNewItem,LPCTSTR lpNewItem);
int __stdcall InternalGetWindowText(HWND hWnd,LPWSTR lpString,int nMaxCount);
int __stdcall IntersectRect(LPRECT lprcDst,const RECT* lprcSrc1,const RECT* lprcSrc2);
int __stdcall InvalidateRect(HWND hWnd,const RECT* lpRect,BOOL bErase);
int __stdcall InvalidateRgn(HWND hWnd,HRGN hRgn,BOOL bErase);
int __stdcall InvertRect(HDC hDC,const RECT* lprc);
int __stdcall IsCharAlpha(TCHAR ch);
int __stdcall IsCharAlphaNumeric(TCHAR ch);
int __stdcall IsCharAlphaNumericA(TCHAR char);
int __stdcall IsCharAlphaNumericW(TCHAR char);
int __stdcall IsCharLower(TCHAR ch);
int __stdcall IsCharLowerA(TCHAR char);
int __stdcall IsCharUpper(TCHAR ch);
int __stdcall IsChild(HWND hWndParent,HWND hWnd);
int __stdcall IsClipboardFormatAvailable(UINT format);
BOOL __stdcall IsDialogMessage(HWND hDlg,LPMSG lpMsg);
BOOL __stdcall IsDialogMessageA(HWND hDlg,LPMSG lpMsg);
BOOL __stdcall IsDialogMessageW(HWND hDlg,LPMSG lpMsg);
int __stdcall IsDlgButtonChecked(HWND hDlg,int nIDButton);
int __stdcall IsGUIThread(BOOL bConvert);
int __stdcall IsHungAppWindow(HWND hWnd);
int __stdcall IsIconic(HWND hWnd);
int __stdcall IsMenu(HMENU hMenu);
int __stdcall IsProcessDPIAware();
int __stdcall IsRectEmpty(const RECT* lprc);
int __stdcall IsTouchWindow(HWND hWnd,PULONG pulFlags);
int __stdcall IsWinEventHookInstalled(DWORD event);
int __stdcall IsWindow(HWND hWnd);
int __stdcall IsWindowEnabled(HWND hWnd);
int __stdcall IsWindowUnicode(HWND hWnd);
int __stdcall IsWindowVisible(HWND hWnd);
int __stdcall IsWow64Message();
int __stdcall IsZoomed(HWND hWnd);
int __stdcall KillTimer(HWND hWnd,UINT_PTR nIDEvent);
HACCEL __stdcall LoadAccelerators(HINSTANCE hInstance,LPCSTR lpTableName);
HACCEL __stdcall LoadAcceleratorsA(HINSTANCE hInstance,LPCSTR lpTableName);
HACCEL __stdcall LoadAcceleratorsW(HINSTANCE hInstance,LPCWSTR lpTableName);
int __stdcall LoadBitmap(HINSTANCE hInstance,LPCTSTR lpBitmapName);
int __stdcall LoadBitmapA(HINSTANCE hInstance,LPCTSTR lpBitmapName);
int __stdcall LoadBitmapW(HINSTANCE hInstance,LPCTSTR lpBitmapName);
HCURSOR __stdcall LoadCursor(HINSTANCE hInstance,LPCTSTR lpCursorName);
HCURSOR __stdcall LoadCursorA(HINSTANCE hInstance,LPCTSTR lpCursorName);
int __stdcall LoadCursorFromFile(LPCTSTR lpFileName);
int __stdcall LoadCursorFromFileA(LPCTSTR lpFileName);
int __stdcall LoadCursorFromFileW(LPCTSTR lpFileName);
HCURSOR __stdcall LoadCursorW(HINSTANCE hInstance,LPCTSTR lpCursorName);
HICON __stdcall LoadIcon(HINSTANCE hInstance,LPCSTR lpIconName);
HICON __stdcall LoadIconA(HINSTANCE hInstance,LPCSTR lpIconName);
HICON __stdcall LoadIconW(HINSTANCE hInstance,LPCSTR lpIconName);
int __stdcall LoadImage(HINSTANCE hinst,LPCTSTR lpszName,UINT uType,int cxDesired,int cyDesired,UINT fuLoad);
int __stdcall LoadImageA(HINSTANCE hinst,LPCTSTR lpszName,UINT uType,int Width,int Height,UINT Options);
int __stdcall LoadImageW(HINSTANCE hinst,LPCTSTR lpszName,UINT uType,int Width,int Height,UINT Options);
int __stdcall LoadKeyboardLayout(LPCTSTR pwszKLID,UINT Flags);
int __stdcall LoadKeyboardLayoutA(LPCTSTR lpwszKLID,UINT Flags);
int __stdcall LoadKeyboardLayoutW(LPCTSTR lpwszKLID,UINT Flags);
int __stdcall LoadMenu(HINSTANCE hInstance,LPCTSTR lpMenuName);
int __stdcall LoadMenuA(HINSTANCE hInstance,LPCTSTR lpMenuName);
int __stdcall LoadMenuIndirect(CONST MENUTEMPLATE* lpMenuTemplate);
int __stdcall LoadMenuIndirectA(CONST MENUTEMPLATE* lpMenuTemplate);
int __stdcall LoadMenuIndirectW(CONST MENUTEMPLATE* lpMenuTemplate);
int __stdcall LoadMenuW(HINSTANCE hInstance,LPCTSTR lpMenuName);
int __stdcall LoadString(HINSTANCE hInstance,UINT uID,LPTSTR lpBuffer,int nBufferMax);
int __stdcall LoadStringA(HINSTANCE hInstance,UINT uID,LPTSTR lpBuffer,int nBufferMax);
int __stdcall LoadStringW(HINSTANCE hInstance,UINT uID,LPTSTR lpBuffer,int nBufferMax);
int __stdcall LockSetForegroundWindow(UINT uLockCode);
int __stdcall LockWindowUpdate(HWND hWndLock);
int __stdcall LockWorkStation();
int __stdcall LogicalToPhysicalPoint(HWND hWnd,LPPOINT lpPoint);
int __stdcall LookupIconIdFromDirectory(PBYTE presbits,BOOL fIcon);
int __stdcall LookupIconIdFromDirectoryEx(PBYTE presbits,BOOL fIcon,int cxDesired,int cyDesired,UINT Flags);
int __stdcall MapDialogRect(HWND hDlg,LPRECT IpRect);
int __stdcall MapVirtualKey(UINT uCode,UINT uMapType);
int __stdcall MapVirtualKeyA(UINT uCode,UINT uMapType);
int __stdcall MapVirtualKeyEx(UINT uCode,UINT uMapType,HKL dwhkl);
int __stdcall MapVirtualKeyExA(UINT uCode,UINT uMapType,HKL dwhkl);
int __stdcall MapVirtualKeyExW(UINT uCode,UINT uMapType,HKL dwhkl);
int __stdcall MapVirtualKeyW(UINT uCode,UINT uMapType);
int __stdcall MapWindowPoints(HWND hWndFrom,HWND hWndTo,LPPOINT lpPoints,UINT cPoints);
int __stdcall MenuItemFromPoint(HWND hWnd,HMENU hMenu,POINT ptScreen);
int __stdcall MessageBeep(UINT uType);
int __stdcall MessageBox(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType);
int __stdcall MessageBoxA(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType);
int __stdcall MessageBoxEx(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType,WORD wLanguageId);
int __stdcall MessageBoxExA(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType,WORD wLanguageId);
int __stdcall MessageBoxExW(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType,WORD wLanguageId);
int __stdcall MessageBoxIndirect(const LPMSGBOXPARAMS lpMsgBoxParams);
int __stdcall MessageBoxIndirectA(const LPMSGBOXPARAMS lpMsgBoxParams);
int __stdcall MessageBoxIndirectW(const LPMSGBOXPARAMS lpMsgBoxParamsW);
int __stdcall MessageBoxTimeout(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType,WORD wLanguageId,DWORD dwMilliseconds);
int __stdcall MessageBoxW(HWND hWnd,LPCTSTR lpText,LPCTSTR lpCaption,UINT uType);
int __stdcall ModifyMenu(HMENU hMnu,UINT uPosition,UINT uFlags,UINT_PTR uIDNewItem,LPCTSTR lpNewItem);
int __stdcall ModifyMenuA(HMENU hMenu,UINT uPosition,UINT uFlags,UINT_PTR uIDNewItem,LPCTSTR lpNewItem);
int __stdcall ModifyMenuW(HMENU hMenu,UINT uPosition,UINT uFlags,UINT_PTR uIDNewItem,LPCTSTR lpNewItem);
int __stdcall MonitorFromPoint(POINT pt,DWORD dwFlags);
int __stdcall MonitorFromRect(LPCRECT lprc,DWORD dwFlags);
int __stdcall MonitorFromWindow(DWORD hWnd,DWORD dwFlags);
int __stdcall MonitorFromWindow(HWND hwnd,DWORD dwFlags);
int __stdcall MoveWindow(HWND hWnd,int X,int Y,int nWidth,int nHeight,BOOL bRepaint);
int __stdcall MsgWaitForMultipleObjects(DWORD nCount,const HANDLE* pHandles,BOOL fWaitAll,DWORD dwMilliseconds,DWORD dwWakeMask);
int __stdcall MsgWaitForMultipleObjectsEx(DWORD nCount,const HANDLE* pHandles,DWORD dwMilliseconds,DWORD dwWakeMask,DWORD dwFlags);
int __stdcall NotifyWinEvent(DWORD event,HWND hwnd,LONG idObject,LONG idChild);
int __stdcall OemKeyScan(WORD wOemChar);
int __stdcall OemToChar(LPCSTR lpszSrc,LPTSTR lpszDst);
int __stdcall OemToCharA(LPCSTR lpszSrc,LPTSTR lpszDst);
int __stdcall OemToCharBuff(LPCTSTR lpszSrc,LPTSTR lpszDst,DWORD cchDstLength);
int __stdcall OemToCharBuffA(LPCTSTR lpszSrc,LPTSTR lpszDst,DWORD cchDstLength);
int __stdcall OemToCharBuffW(LPCTSTR lpszSrc,LPTSTR lpszDst,DWORD cchDstLength);
int __stdcall OemToCharW(LPCSTR lpszSrc,LPTSTR lpszDst);
int __stdcall OffsetRect(LPRECT lprc,int dx,int dy);
int __stdcall OpenClipboard(HWND hWndNewOwner);
int __stdcall OpenDesktop(LPTSTR lpszDesktop,DWORD dwFlags,BOOL fInherit,DWORD dwDesiredAccess);
int __stdcall OpenIcon(HWND hWnd);
int __stdcall OpenInputDesktop(DWORD dwFlags,BOOL fInherit,DWORD dwDesiredAccess);
int __stdcall OpenWindowStation(LPTSTR lpszWinSta,BOOL fInherit,DWORD dwDesiredAccess);
int __stdcall PackDDElParam(UINT msg,UINT_PTR uiLo,UINT_PTR uiHi);
int __stdcall PaintDesktop(HDC hDC);
int __stdcall PeekMessage(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax,UINT wRemoveMsg);
int __stdcall PeekMessageA(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax,UINT wRemoveMsg);
int __stdcall PeekMessageW(LPMSG lpMsg,HWND hWnd,UINT wMsgFilterMin,UINT wMsgFilterMax,UINT wRemoveMsg);
int __stdcall PhysicalToLogicalPoint(HWND hWnd,LPPOINT lpPoint);
int __stdcall PostMessage(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall PostMessageA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM Param);
int __stdcall PostMessageW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM Param);
int __stdcall PostQuitMessage(int nExitCode);
int __stdcall PostThreadMessage(DWORD idThread,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall PostThreadMessageA(DWORD idThread,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall PostThreadMessageW(DWORD idThread,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall PrintWindow(HWND hwnd,HDC hdcBlt,UINT nFlags);
int __stdcall PrivateExtractIcons(LPCTSTR lpszFile,int nIconIndex,int cxIcon,int cyIcon,HICON* phicon,UINT* piconid,UINT nIcons,UINT flags);
int __stdcall PtInRect(const RECT* lprc,POINT pt);
int __stdcall RealChildWindowFromPoint(HWND hwndParent,POINT ptParentClientCoords);
int __stdcall RealGetWindowClass(HWND hwnd,LPTSTR pszType,UINT cchType);
int __stdcall RedrawWindow(HWND hWnd,const RECT* lprcUpdate,HRGN hrgnUpdate,UINT flags);
ATOM __stdcall RegisterClass(CONST WNDCLASS* lpWndClass);
ATOM __stdcall RegisterClassA(CONST WNDCLASS* lpWndClass);
ATOM __stdcall RegisterClassW(const WNDCLASS* lpWndClass);
ATOM __stdcall RegisterClassEx(CONST WNDCLASSEX* lpwcx);
ATOM __stdcall RegisterClassExA(CONST WNDCLASSEX* lpWndClassEx);
ATOM __stdcall RegisterClassExW(CONST WNDCLASSEX* lpWndClassEx);
int __stdcall RegisterClassW(CONST WNDCLASS* lpWndClass);
int __stdcall RegisterClipboardFormat(LPCTSTR lpszFormat);
int __stdcall RegisterClipboardFormatA(LPCTSTR lpszFormat);
int __stdcall RegisterClipboardFormatW(LPCTSTR lpszFormat);
int __stdcall RegisterDeviceNotification(HANDLE hRecipient,LPVOID NotificationFilter,UINT Flags);
int __stdcall RegisterHotKey(HWND hWnd,int id,UINT fsModifiers,UINT vk);
int __stdcall RegisterPowerSettingNotification(HANDLE hRecipient,LPCGUID PowerSettingGuid,UINT Flags);
int __stdcall RegisterRawInputDevices(PCRAWINPUTDEVICE pRawInputDevices,UINT uiNumDevices,UINT cbSize);
int __stdcall RegisterShellHookWindow(HWND hWnd);
int __stdcall RegisterTouchWindow(HWND hWnd,ULONG ulFlags);
int __stdcall RegisterWindowMessage(LPCTSTR lpString);
int __stdcall RegisterWindowMessageA(LPCTSTR lpString);
int __stdcall RegisterWindowMessageW(LPCTSTR lpString);
int __stdcall ReleaseCapture();
int __stdcall ReleaseDC(HWND hWnd,HDC hDC);
int __stdcall RemoveClipboardFormatListener(HWND hwnd);
int __stdcall RemoveMenu(HMENU hMenu,UINT uPosition,UINT uFlags);
int __stdcall RemoveProp(HWND hWnd,LPCTSTR lpString);
int __stdcall RemovePropA(HWND hWnd,LPCTSTR lpString);
int __stdcall RemovePropW(HWND hWnd,LPCTSTR lpString);
int __stdcall ReplyMessage(LRESULT lResult);
int __stdcall ReuseDDElParam(LPARAM lParam,UINT msgIn,UINT msgOut,UINT_PTR uiLo,UINT_PTR uiHi);
int __stdcall ScreenToClient(HWND hWnd,LPPOINT lpPoint);
int __stdcall ScrollDC(HDC hDC,int dx,int dy,const RECT* lprcScroll,const RECT* lprcClip,HRGN hrgnUpdate,LPRECT lprcUpdate);
int __stdcall ScrollWindow(HWND hWnd,int XAmount,int YAmount,const RECT* lpRect,const RECT* lpClipRect);
int __stdcall ScrollWindowEx(HWND hWnd,int dx,int dy,const RECT* prcScroll,const RECT* prcClip,HRGN hrgnUpdate,LPRECT prcUpdate,UINT flags);
int __stdcall SendDlgItemMessage(HWND hDlg,int nIDDlgItem,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SendDlgItemMessageA(HWND hDlg,int nIDDlgItem,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SendInput(UINT nInputs,LPINPUT pInputs,int cbSize);
int __stdcall SendMessage(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SendMessageA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM Param);
int __stdcall SendMessageCallback(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,SENDASYNCPROC lpCallBack,ULONG_PTR dwData);
int __stdcall SendMessageCallbackA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,SENDASYNCPROC lpResultCallBack,ULONG_PTR dwData);
int __stdcall SendMessageCallbackW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,SENDASYNCPROC lpResultCallBack,ULONG_PTR dwData);
int __stdcall SendMessageTimeout(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,UINT fuFlags,UINT uTimeout,PDWORD_PTR lpdwResult);
int __stdcall SendMessageTimeoutA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,UINT fuFlags,UINT uTimeout,PDWORD_PTR lpdwResult);
int __stdcall SendMessageTimeoutW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam,UINT fuFlags,UINT uTimeout,PDWORD_PTR lpdwResult);
int __stdcall SendMessageW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM Param);
int __stdcall SendNotifyMessage(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SendNotifyMessageA(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SendNotifyMessageW(HWND hWnd,UINT Msg,WPARAM wParam,LPARAM lParam);
int __stdcall SetActiveWindow(HWND hWnd);
int __stdcall SetCapture(HWND hWnd);
int __stdcall SetCaretBlinkTime(UINT uMSeconds);
int __stdcall SetCaretPos(int X,int Y);
int __stdcall SetClassLong(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetClassLongA(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetClassLongW(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetClassWord(HWND hWnd,int nIndex,WORD wNewWord);
int __stdcall SetClipboardData(UINT uFormat,HANDLE hMem);
int __stdcall SetClipboardViewer(HWND hWndNewViewer);
int __stdcall SetCursor(HCURSOR hCursor);
int __stdcall SetCursorPos(int X,int Y);
int __stdcall SetDlgItemInt(HWND hDlg,int nIDDlgItem,UINT uValue,BOOL bSigned);
int __stdcall SetDlgItemText(HWND hDlg,int nIDDlgItem,LPCTSTR lpString);
int __stdcall SetDlgItemTextA(HWND hDlg,int nIDDlgItem,LPCTSTR lpString);
int __stdcall SetDlgItemTextW(HWND hDlg,int nIDDlgItem,LPCTSTR lpString);
int __stdcall SetDoubleClickTime(UINT uInterval);
int __stdcall SetFocus(HWND hWnd);
int __stdcall SetForegroundWindow(HWND hWnd);
int __stdcall SetGestureConfig(HWND hwnd,DWORD dwReserved,UINT cIDs,PGESTURECONFIG pGestureConfig,UINT cbSize);
int __stdcall SetKeyboardState(LPBYTE lpKeyState);
int __stdcall SetLastErrorEx(DWORD dwErrCode,DWORD dwType);
int __stdcall SetLayeredWindowAttributes(HWND hWnd,COLORREF crKey,BYTE bAlpha,DWORD dwFlags);
int __stdcall SetMenu(HWND hWnd,HMENU hMenu);
int __stdcall SetMenuContextHelpId(HMENU hmenu,DWORD dwContextHelpId);
int __stdcall SetMenuDefaultItem(HMENU hMenu,UINT uItem,UINT fByPos);
int __stdcall SetMenuInfo(HMENU hmenu,LPCMENUINFO lpcmi);
int __stdcall SetMenuItemBitmaps(HMENU hMenu,UINT uPosition,UINT uFlags,HBITMAP hBitmapUnchecked,HBITMAP hBitmapChecked);
int __stdcall SetMenuItemInfo(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall SetMenuItemInfoA(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall SetMenuItemInfoW(HMENU hMenu,UINT uItem,BOOL fByPosition,LPMENUITEMINFO lpmii);
int __stdcall SetMessageExtraInfo(LPARAM lParam);
int __stdcall SetParent(HWND hWndChild,HWND hWndNewParent);
int __stdcall SetPhysicalCursorPos(int X,int Y);
int __stdcall SetProcessDPIAware();
int __stdcall SetProcessDefaultLayout(DWORD dwDefaultLayout);
int __stdcall SetProcessWindowStation(HWINSTA hWinSta);
int __stdcall SetProp(HWND hWnd,LPCTSTR lpString,HANDLE hData);
int __stdcall SetPropA(HWND hWnd,LPCTSTR lpString,HANDLE hData);
int __stdcall SetPropW(HWND hWnd,LPCTSTR lpString,HANDLE hData);
int __stdcall SetRect(LPRECT lprc,int xLeft,int yTop,int xRight,int yBottom);
int __stdcall SetRectEmpty(LPRECT lprc);
int __stdcall SetScrollInfo(HWND hWnd,int fnBar,LPCSCROLLINFO lpsi,BOOL fRedraw);
int __stdcall SetScrollPos(HWND hWnd,int nBar,int nPos,BOOL bRedraw);
int __stdcall SetScrollRange(HWND hWnd,int nBar,int nMinPos,int nMaxPos,BOOL bRedraw);
int __stdcall SetSysColors(int cElements,const INT* lpaElements,const COLORREF* lpaRgbValues);
int __stdcall SetSystemCursor(HCURSOR hcur,DWORD id);
int __stdcall SetThreadDesktop(HDESK hDesktop);
int __stdcall SetTimer(HWND hWnd,UINT_PTR nIDEvent,UINT uElapse,TIMERPROC lpTimerFunc);
int __stdcall SetUserObjectInformation(HANDLE hObj,int nIndex,PVOID pvInfo,DWORD nLength);
int __stdcall SetUserObjectSecurity(HANDLE hObj,PSECURITY_INFORMATION pSIRequested,PSECURITY_DESCRIPTOR pSID);
int __stdcall SetWinEventHook(UINT eventMin,UINT eventMax,HMODULE hmodWinEventProc,WINEVENTPROC lpfnWinEventProc,DWORD idProcess,DWORD idThread,DWORD dwflags);
int __stdcall SetWindowContextHelpId(HWND hWnd,DWORD dwContextHelpId);
int __stdcall SetWindowDisplayAffinity(HWND hWnd,DWORD dwAffinity);
int __stdcall SetWindowLong(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetWindowLongA(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetWindowLongW(HWND hWnd,int nIndex,LONG dwNewLong);
int __stdcall SetWindowPlacement(HWND hWnd,WINDOWPLACEMENT* lpwndpl);
int __stdcall SetWindowPos(HWND hWnd,HWND hWndInsertAfter,int X,int Y,int cx,int cy,UINT uFlags);
int __stdcall SetWindowRgn(HWND hWnd,HRGN hRgn,BOOL bRedraw);
int __stdcall SetWindowText(HWND hWnd,LPCTSTR lpString);
int __stdcall SetWindowTextA(HWND hwnd,LPCTSTR lpString);
int __stdcall SetWindowTextW(HWND hwnd,LPCTSTR lpString);
int __stdcall SetWindowsHookEx(int idHook,HOOKPROC lpfn,HINSTANCE hMod,DWORD dwThreadId);
int __stdcall SetWindowsHookExA(int idHook,HOOKPROC lpfn,HINSTANCE hMod,DWORD dwThreadId);
int __stdcall SetWindowsHookExW(int idHook,HOOKPROC lpfn,HINSTANCE hMod,DWORD dwThreadId);
int __stdcall ShowCaret(HWND hWnd);
int __stdcall ShowCursor(BOOL bShow);
int __stdcall ShowOwnedPopups(HWND hWnd,BOOL fShow);
int __stdcall ShowScrollBar(HWND hWnd,int wBar,BOOL bShow);
int __stdcall ShowWindow(HWND hWnd,int nCmdShow);
int __stdcall ShowWindowAsync(HWND hWnd,int nCmdShow);
int __stdcall ShutdownBlockReasonCreate(HWND hWnd,LPCWSTR pwszReason);
int __stdcall ShutdownBlockReasonDestroy(HWND hWnd);
int __stdcall ShutdownBlockReasonQuery(HWND hWnd,LPWSTR pwszBuff,DWORD* pcchBuff);
int __stdcall SoundSentry();
int __stdcall SubtractRect(LPRECT lprcDst,const RECT* lprcSrc1,const RECT* lprcSrc2);
int __stdcall SwapMouseButton(BOOL fSwap);
int __stdcall SwitchDesktop(HDESK hDesktop);
int __stdcall SwitchToThisWindow(HWND hWnd,BOOL fAltTab);
int __stdcall SystemParametersInfo(long uiAction,UINT uiParam,PVOID pvParam,long fWinIni);
int __stdcall SystemParametersInfoA(long uiAction,UINT uiParam,PVOID pvParam,long fWinIni);
int __stdcall SystemParametersInfoW(long uiAction,UINT uiParam,PVOID pvParam,long fWinIni);
int __stdcall TabbedTextOut(HDC hDC,int X,int Y,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions,int nTabOrigin);
int __stdcall TabbedTextOutA(HDC hDC,int X,int Y,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions,int nTabOrigin);
int __stdcall TabbedTextOutW(HDC hDC,int X,int Y,LPCTSTR lpString,int nCount,int nTabPositions,const LPINT lpnTabStopPositions,int nTabOrigin);
int __stdcall TileWindows(HWND hwndParent,UINT wHow,RECT* lpRect,UINT cKids,const HWND* lpKids);
int __stdcall ToAscii(UINT uVirtKey,UINT uScanCode,PBYTE lpKeyState,LPWORD lpChar,UINT uFlags);
int __stdcall ToAsciiEx(UINT uVirtKey,UINT uScanCode,PBYTE lpKeyState,LPWORD lpChar,UINT uFlags,HKL dwhkl);
int __stdcall ToUnicode(UINT wVirtKey,UINT wScanCode,const PBYTE lpKeyState,LPWSTR pwszBuff,int cchBuff,UINT wFlags);
int __stdcall ToUnicodeEx(UINT wVirtKey,UINT wScanCode,const PBYTE lpKeyState,LPWSTR pwszBuff,int cchBuff,UINT wFlags,HKL dwhkl);
int __stdcall TrackMouseEvent(LPTRACKMOUSEEVENT pTrackMouseEvent);
int __stdcall TrackPopupMenu(HMENU hMenu,UINT uFlags,int X,int Y,int nReserved,HWND hWnd,CONST RECT* prcRect);
int __stdcall TrackPopupMenuEx(HMENU hmenu,UINT fuFlags,int x,int Y,HWND hWnd,LPTPMPARAMS lptpm);
int __stdcall TranslateAcceleratorA(HWND hWnd,HACCEL hAccTable,LPMSG lpMsg);
int __stdcall TranslateAcceleratorW(HWND hWnd,HACCEL hAccTable,LPMSG lpMsg);
int __stdcall TranslateAccelerator(HWND hWnd,HACCEL hAccTable,LPMSG lpMsg);
int __stdcall TranslateMDISysAccel(HWND hWndClient,LPMSG lpMsg);
int __stdcall TranslateMessage(const MSG* lpMsg);
int __stdcall UnhookWinEvent(HWINEVENTHOOK hWinEventHook);
int __stdcall UnhookWindowsHookEx(HHOOK hhk);
int __stdcall UnionRect(LPRECT lprcDst,const RECT* lprcSrc1,const RECT* lprcSrc2);
int __stdcall UnloadKeyboardLayout(HKL hkl);
int __stdcall UnpackDDElParam(UINT msg,LPARAM lParam,PUINT_PTR puiLo,PUINT_PTR puiHi);
int __stdcall UnregisterClass(LPCTSTR lpClassName,HINSTANCE hInstance);
int __stdcall UnregisterClassA(DWORD lpClassName,DWORD hInstance);
int __stdcall UnregisterClassA(LPCTSTR lpClassName,HINSTANCE hInstance);
int __stdcall UnregisterClassW(LPCTSTR lpClassName,HINSTANCE hInstance);
int __stdcall UnregisterDeviceNotification(HDEVNOTIFY Handle);
int __stdcall UnregisterHotKey(HWND hWnd,int id);
int __stdcall UnregisterPowerSettingNotification(HPOWERNOTIFY Handle);
int __stdcall UnregisterTouchWindow(HWND hWnd);
int __stdcall UpdateLayeredWindow(HWND hwnd,HDC hdcDst,POINT* pptDst,SIZE* psize,HDC hdcSrc,POINT* pptSrc,COLORREF crKey,BLENDFUNCTION* pblend,DWORD dwFlags);
int __stdcall UpdateLayeredWindowIndirect(HWND hwnd,const UPDATELAYEREDWINDOWINFO* pULWInfo);
int __stdcall UpdateWindow(HWND hWnd);
int __stdcall UserHandleGrantAccess(HANDLE hUserHandle,HANDLE hJob,BOOL bGrant);
int __stdcall ValidateRect(HWND hWnd,const RECT* lpRect);
int __stdcall ValidateRgn(HWND hWnd,HRGN hRgn);
int __stdcall VkKeyScan(TCHAR ch);
int __stdcall VkKeyScanA(TCHAR ch);
int __stdcall VkKeyScanEx(TCHAR ch,HKL dwhkl);
int __stdcall VkKeyScanW(TCHAR ch);
int __stdcall WaitForInputIdle(HANDLE hProcess,DWORD dwMilliseconds);
int __stdcall WaitMessage();
int __stdcall WinHelp(HWND hWndMain,LPCTSTR lpszHelp,UINT uCommand,ULONG_PTR dwData);
int __stdcall WinHelpA(HWND hWndMain,LPCTSTR lpszHelp,UINT uCommand,ULONG_PTR wData);
int __stdcall WinHelpW(HWND hWndMain,LPCTSTR lpszHelp,UINT uCommand,ULONG_PTR wData);
int __stdcall WindowFromDC(HDC hDC);
int __stdcall WindowFromPhysicalPoint(POINT Point);
int __stdcall WindowFromPoint(POINT Point);
int __stdcall keybd_event(BYTE bVk,BYTE bScan,DWORD dwFlags,ULONG_PTR dwExtraInfo);
int __stdcall mouse_event(DWORD dwFlags,DWORD dx,DWORD dy,DWORD dwData,ULONG_PTR dwExtraInfo);
int __stdcall toascii(DWORD char);